Case study - Java functional programming using Vavr.
p2w34/blog pull request #1
Opened 2020-03-29 19:41 UTC by p2w34

2020-03-30 17:41 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +Most Vavr tutorials show how to use Vavr primitives but they do not provide intuition on how to write whole applications.
Just a single sentence about what Vavr is + a link :)

2020-03-30 18:51 UTC, PawelLipski requested changes
Good job! review done

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +From all such 'somethings' first thing which comes to my mind is 'pipeline'.
Oh ok, I see the picture below implies linear flow

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +- orange - with side effects (especially throwing errors),
Hmm the mention about throwing errors here is a bit confusing (esp. wrt. the distinction b/w red and orange)... but I hope it'll get clearer down the way

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +writing to a file, no possibility to input parameters, etc.
Wrt. `input parameters`: that's a bit unclear coz a program can get parameters at the beginning and still remain purely functional... pls specify what you mean here (e.g. reading extra input from the file or providing parameters interactively during the execution)?

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +Should any error occur, it will be wrapped (with help of Vavr) into a proper type and returned (not thrown) from a method.
`s/with help/with the help`

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +![service_flow](images/service_flow.png)
Hmm I'd consistently use verbs and not nouns (like `DB Service` or `Security token`) to name the orange boxes (pipeline stages).

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +- get last 'polling status' from S3
`s/last/latest` (more unambiguous)

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +(note: of course, when you base your pipeline on Try, conversion to Either is not necessary).
Maybe you could factor out `Try` completely to simplify the narrative?

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +    Boolean publishItem(ItemData item) throws RuntimeException;
Hmm does it make sense to declare `throws` for `RuntimeException`? In a sense, every method in Java `throws RuntimeException` by default ;)

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +(note: of course, when you base your pipeline on Try, conversion to Either is not necessary).
Or only keep it inside method implementation where needed, but instantly convert to Either? i.e. never exposing it from any method

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +These are primitives like Stream.continually(), takeWhile(), dropWhile() and find().
Nit: format method names as `code`

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +The io.vavr.collection.Stream implementation is a lazy linked list.**
Btw this list is unidirectional, right (you can only go forward in the stream but never backward)? Maybe worth mentioning if so

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +            pr -> anyServiceStream.serviceCall(pr) # it returns false for the first three calls, true for the rest
`#` for comments? ;)

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +            pr -> anyServiceList.serviceCall(pr) # it returns false for the first three calls, true for the rest
`anyServiceList::serviceCall`?

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +        .find(processingResult -> processingResult.isResult() == false);
`.find(processingResult -> !processingResult.isResult())`? Or even `.findNot(processingResult::isResult)` if such method exists

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +        .find(processingResult -> processingResult.isResult() == false);
`isResult`... hmm what does this method return actually? ;D what does it mean when `processingResult IS NOT result`? ;)

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +        .find(processingResult -> processingResult.isResult() == false);
Maybe `isSuccessful` or sth like that instead?

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +One might observe that lazy implementation of Stream class causes that anyServiceStream.serviceCall(pr)
`code` formatting

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +            availableItemsResponse = fetchResult.get();
Make it clear somehow that `get()` returns the Right part (maybe `.getRight()` if exists?)

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +        } while (availableItemsResponse.getHasMore() == true);
Remove `== true`

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +        } while (availableItemsResponse.getHasMore() == true);
Plus rename the method to `hasMore` if under your control

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +                .map(__ -> true);
Maybe put a comment that `__` name indicates that the param is to be ignored

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +and then plugged into the pipeline using map() instead of peek().
Explain the difference b/w the effect of `peek` and `map`

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +        .onFailure(t -> logError(t, "Service failuer"))
Typo

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +    return Option.of(label)
`ofNullable`?

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +            .map(__ -> true)
`.map(__ -> true).getOrElse(false)` => `.isPresent()`?

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +It may also serve as proof that it is not necessary to even mention (in)famous 'm-word' to talk about FP usage in practice!
Hmmm I don't think the joke is going to be very clear... esp. to the people who, well, don't operate on monads on a daily basis (and I think that might be the target group) ;) what adds to the confusion is proximity of another m-word `microservices` :/

2020-03-30 18:51 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/code-examples/src/test/java/com/pbroda/codesnippets/vavr/LoopCaseStudy.java
> +//@Value
Remove or uncomment

2020-03-30 20:37 UTC, ArturSkowronski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +public static <T> Either<Throwable, T> logInfo(T rightValue, String message) {...}
Isn't that a bit contrived example? It's hard for me to imagine somebody writing logic like that.

2020-03-30 20:37 UTC, ArturSkowronski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +It is built without any frameworks apart from Guice to provide dependency injection, but this is irrelevant here.
I'd get rid of that sentence. It's nice that you built microservice without frameworks, but as you said - it's irrelevant there

2020-03-30 20:37 UTC, ArturSkowronski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +What is important is that contacting them is a side effect.
Maybe merge those two sentences?

'All external services are exposed through REST, but what truly matter is that contacting them is a side effect.'

2020-03-30 20:37 UTC, ArturSkowronski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +Since Try might be treated as a specific case of Either, for the needs of this case study it does not really matter which one we choose.
Maybe stick to one then?

2020-03-30 20:37 UTC, ArturSkowronski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +        return fetchAndPublishResult.isLeft() ||
This code is basically ugly to somebody who isn't already fan of FP approach. It's a bit preaching to the already converted. Maybe that the goal.

2020-03-30 20:37 UTC, ArturSkowronski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +It may also serve as proof that it is not necessary to even mention (in)famous 'm-word' to talk about FP usage in practice!
I agree with you there, but I have one question to @p2w34 - who is really a target of that post? Cause after reading it, I see that it will appeal to people who like FP, need to write in Java for some reason and want to use Vavr to emulate some techniques. Did I recognize correctly? Cause for newbies, I lack a bit of a better explanation of how this approach helps.

2020-03-30 23:12 UTC, p2w34 reviewed
Thank you for your comments. I hope that I was able to apply your suggestions/reply to the comments.
I will have to yet address Artur's question - let me think about it more.

2020-03-30 23:12 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +It may also serve as proof that it is not necessary to even mention (in)famous 'm-word' to talk about FP usage in practice!
Joke removed.

@ArturSkowronski - I am very happy seeing a comment like this. It is clear advice that I should modify Intro/Summary.
This post is meant for regular (regular meaning that on a daily basis they write Java code, it is not about seniority level) Java developers, who heard/even bought books about FP in Java, they might have used Vavr here and there, but still they do not know how to combine this knowledge so that they write entire applications in this style. And I am writing it based on my own experience - I have never used any Scala/Haskell, etc. But I do see the benefits of FP and I would like to share what I already know, in the simplest possible form.

2020-03-30 23:12 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +        return fetchAndPublishResult.isLeft() ||
I am not sure whether I understand your comment. For most people, the code before refactoring is for sure more clear, but I wanted to present how one can write it using Vavr the proper way.

2020-03-30 23:12 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +public static <T> Either<Throwable, T> logInfo(T rightValue, String message) {...}
It is a real example ;/. That is why I wanted to mention here that it is better to avoid such code. Or in your opinion, I should rather remove it?

2020-04-01 22:15 UTC, p2w34 commented
@ArturSkowronski - I just changed the introduction - I added information about the target audience.
Do you think that now it clarifies the whole idea behind this post?

2020-04-10 21:02 UTC, PawelLipski requested changes

2020-04-10 21:02 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +(note: of course, when you base your pipeline on ```Try```, conversion to ```Either``` is not necessary).
Side note: IMO `Try` generally sucks (same in Scala) coz (unlike `Either`) it doesn't allow for specifying upper bound on the exception type... just `Throwable` is all we've got :hankey:

2020-04-10 21:02 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +    Boolean publishItem(ItemData item);
Nit: primitive `boolean` instead?

2020-04-11 11:46 UTC, PawelLipski requested changes

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +@Value
Hmm where's that `@Value` coming from? Maybe it can be safely skipped?

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +And their 'brothers and sister' (```takeUntil()``` etc.).
```suggestion
And their 'brothers and sisters' (```takeUntil()``` etc.).  
```

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +Assume, we want to call two services in a loop (this correspond to the bigger rectangle on the picture).
```suggestion
Assume we want to call two services in a loop (this corresponds to the bigger rectangle on the picture).
```

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +This proceeds in a loop until there is a certain condition met, based on the results of the first call.
```suggestion
This proceeds in a loop until there a certain condition is met, based on the results of the first call.
```

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +Unit tests not only assure us the functionality is correct, but also allow us with experimenting on the way to get a nice result.
```suggestion
Unit tests not only assure us the functionality is correct, but also allow to experiment on the way to get the desired result.
```

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +@Value
Again, `@Value` is unclear here

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +- it is based on the result of the first service call, as already stressed.
Hmmm this second point is a bit a awkward - maybe sth along the lines of `another service call follows in each iteration after the service call that ...`

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +which terminates the loop:
`loop termination condition`?

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +                .map(ignore -> true);
Nit: `__ -> true` maybe, seems that's kinda convention

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +                .flatMap(itemsResponse -> publishAvailableItems(itemsResponse));
```suggestion
                .flatMap(this::publishAvailableItems);
```

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +When logging methods we write are meant to just log messages passed to them, i.e. their signatures are of form:
`When logging methods we write are meant to just log` - this part is unclear

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +It would be still feasible to code it, with for example help of 'suppressed' exceptions, but one might unnecessarily
What do you mean specifically by `suppressed` exceptions? Wrapped into `RuntimeException`?

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +.mapLeft(err -> translateError(err))
`::`?

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +Should any translation of an error be needed at any stage of the pipeline, then simply:
It isn't clear what you specifically mean by `translation`, pls specify

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +## Aspect 4 - exceptions
It might be a good idea to split the post into two parts, it's pretty long

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +What is more, I also consider a good practice wrapping the starting point of an application with ```Try```:
```suggestion
What is more, I also consider it a good practice to wrap the starting point of the application into ```Try```:
```

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +            .filter(allowedLabels::contains)
`.exists(allowedLabels::contains)`? or sth like that

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +            .getOrElse(() -> Either.right(false));
`io.vavr.Option#toEither(L)` instead?

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/code-examples/src/test/java/com/pbroda/codesnippets/vavr/ExternalServiceCall.java
> +public class ExternalServiceCall {
`ExternalServiceCallTest` for clarity that it's test code?

2020-04-11 11:46 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/code-examples/src/test/java/com/pbroda/codesnippets/vavr/LoopBasics.java
> +public class LoopBasics {
Again, `LoopBasicsTest`?

2020-04-13 14:12 UTC, mpociecha commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +However, to not scare the reader off - a basic understanding of FP concepts like immutability or pure functions is sufficient.
Given you started with comma, it should be `reader off, a basic`

2020-04-13 14:14 UTC, mpociecha commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +- green - purely functional (no side effects),
Nitpick: In such cases like this `green - purely` there should be used dashes instead of hyphens (see https://www.grammarly.com/blog/hyphens-and-dashes/)

2020-04-13 17:51 UTC, mpociecha commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +They both present programs as pipelines. A single arrow should be interpreted as a single computational stage (for example a single method),
It could be just `An arrow should be interpreted as a computational stage (for example a single method)`

2020-04-13 21:22 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/code-examples/src/test/java/com/pbroda/codesnippets/vavr/ExternalServiceCall.java
> +public class ExternalServiceCall {
Done

2020-04-13 21:22 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +            .getOrElse(() -> Either.right(false));
`isAllowed() `already returns `Either`.

`.getOrElse()`, and '`Else`' part in particular is for scenario in which `Option.of(label)` returns `None`.

2020-04-13 21:22 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +All external services are exposed through REST, but what truly matters is that contacting them is a side effect.
I admit it is a more sophisticated word but I leave it as it is.

2020-04-13 21:22 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +    Boolean publishItem(ItemData item);
Could be boolean as well, but I think it may stay as it is.

2020-04-13 21:22 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +And their 'brothers and sister' (```takeUntil()``` etc.).
done

2020-04-13 21:22 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +                .map(ignore -> true);
As I already wrote somewhere, ignore is also fine so I leave it as it is.

2020-04-14 08:35 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +It would be still feasible to code it, with for example help of 'suppressed' exceptions, but one might unnecessarily
Wow ok, I didn't know this stuff previously :)

2020-04-14 09:13 UTC, PawelLipski requested changes

2020-04-14 09:13 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +after each such successful operation, update 'polling status' on S3.
`- ` at the start? The intended indent (no pun intended xD) is current unclear here

2020-04-14 09:13 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +@Value
Note that publishing code snippets (as well as tables) in Medium articles sucks a big time (just as many things about Medium's usability): I ended up cooking up Gists for mine recently: https://medium.com/virtuslab/nifty-docker-tricks-for-your-ci-vol-1-c4a36d2192ea

2020-04-14 09:13 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +[here](./code-examples/src/test/java/com/pbroda/codesnippets/vavr/ExternalServiceCall.java).
Update the links (`...Test.java`)

2020-04-14 09:13 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +And their 'brothers and sisters' (```takeUntil()``` etc.).
```suggestion
These include primitives like ```Stream.continually()```, ```takeWhile()```, ```dropWhile()```, ```find()``` and their counterparts like ```takeUntil()``` etc.
```

2020-04-14 09:13 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +[here](./code-examples/src/test/java/com/pbroda/codesnippets/vavr/LoopBasics.java).
`...Test.java`

2020-04-14 09:13 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +```LogError()``` method is supposed to log exceptions, but it would be plausible that ```logError()``` itself would result in an exception.
```suggestion
```logError()``` method is supposed to log exceptions, but it would be plausible that ```logError()``` itself would result in an exception.
```

2020-04-14 09:13 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +In our example, we are in a very comfortable situation in which we allow them to propagate to the very end and log them there - just in one place.
(?)
```suggestion
In our example, we are in a very comfortable situation in which we allow them to propagate to the very top and log them there - just in one place.
```

2020-04-14 09:13 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +Should any translation (rethrowing) of an error be needed at any stage of the pipeline, then simply:
```suggestion
Should any translation (wrapping & rethrowing) of an error be needed at any stage of the pipeline, then simply:
```

2020-04-14 09:13 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +- if there are side effects involved, I would compose code into a pipeline as this allow to propagate exceptions nicely:
```suggestion
- if there are side effects involved, I would compose code into a pipeline as this allows to propagate exceptions nicely:  
```

2020-04-14 09:13 UTC, PawelLipski commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +- if there are side effects involved, I would compose code into a pipeline as this allow to propagate exceptions nicely:
Run the blogpost through Grammarly or sth like that btw

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +Just one remark here. One might argue whether the word 'pipeline' is appropriate or not.
I applied the general remark. This paragraph might seem to be unnecessary but as the idea of the pipeline is at the core of this post, I'd like to leave it as it is.

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +writing to a file, no possibility to interactively input parameters during execution, etc.
Grammarly recommends comma before etc. - leaving as it is.

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +The pipeline, assembled from Vavr primitives, takes care of proper error propagation to the place where the program begins.
+1, but with `entrypoint` written as `entry point`.

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +It is about assembling such pipelines and paying attention to side effects.
Applied

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +
done

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +after each such successful operation, update 'polling status' on S3.
It should be as it is. I hope it will look good on Medium.

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +@Value
Good to know - sounds like a reasonable way of tackling it.

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +[here](./code-examples/src/test/java/com/pbroda/codesnippets/vavr/ExternalServiceCall.java).
Good catch!

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +And their 'brothers and sisters' (```takeUntil()``` etc.).
:1st_place_medal:

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +```LogError()``` method is supposed to log exceptions, but it would be plausible that ```logError()``` itself would result in an exception.
Done

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +In our example, we are in a very comfortable situation in which we allow them to propagate to the very end and log them there - just in one place.
OK, top might be better - applied.

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +Should any translation (rethrowing) of an error be needed at any stage of the pipeline, then simply:
I admit I haven't thought it too well when I added 'rethrowing'. The point is that in Vavr instead of throwing exceptions we use algebraic types. I change it to:
`Should any translation (by analogy to pure Java _rethrowing_ ) of an error be needed at any stage of the pipeline, then simply.`
Also, wrapping is not mandatory in such cases.

2020-04-14 15:31 UTC, p2w34 commented on 2020-03-21-case-study-java-fp-using-vavr/case-study-java-fp-using-vavr.md
> +- if there are side effects involved, I would compose code into a pipeline as this allow to propagate exceptions nicely:
Did it but at this stage only very few minor corrections are needed.

2020-04-14 16:58 UTC, merged